name: xeus-ug4
channels:
  - conda-forge
  - pyviz
dependencies:
  - xeus
# host Dependencies
  - cppzmq
  - xtl
  - nlohmann_json
# build dependencies
  - cmake
# visualization
  - vtk
  - itkwidgets
  - itk
  - matplotlib
  - pyvista
  - bokeh
  - pyviz_comms
  - panel
  - lxml
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - matplotlib
    - pyct
