name: xeus-ug4
channels:
  - conda-forge
  - pyviz
dependencies:
  - xeus
# host Dependencies
  - cppzmq
  - xtl
  - nlohmann_json
# build dependencies
  - cmake
# visualization
  - vtk
  - itkwidgets>=0.25.2
  - itk
  - matplotlib
  - pyvista
  
